### ISSUE TITLE
requested templates TODO list 

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/intermine-soymine#18]
==========
GENOMICS
- [ ]  Region ==> Sequence
not totally sure if it's possible using a template query, but I think this one would be best done with the Regions pane

- [x] Region ==> Contained genes
- [x] Region ==> Contained markers
- [x] Region ==> Contained GWAS features
First two could be done with the Regions pane, but also can be done in templates, so I've created example versions for
all three.

==========
GENE PRODUCTS
- [x] Genes ==> CDS sequence
- [x] Genes ==> Protein sequence

did "transcripts" for CDS since I don't think we currently have a way to return the UTR-excluded version, but these two are now implemented.
  
- [ ] Genes ==> Noncoding RNA
- [ ] Genes ==> Protein-coding genes
- [ ] Genes ==> Transposable elements

not %100 sure but I think the only Genes we have in soymine currently are protein coding genes, so there is currently not much point to having these three, but we could certainly revisit if we want to import other classes of genes from somewhere.

==========
COMPARISON
- [x] Genes ==> Homologs
did this one

- [x] Region ==> Syntenic region
Hmm, I can't seem to find syntenic regions either in soymine or legumemine though I'm pretty sure we used to; will submit an issue (#17) for Sam to revisit when he returns.

==========
FUNCTION
- [x]  GO term ==> Genes
- [x] Genes ==> GO terms
- [x] Functional descriptor ==> Genes
- [ ] Keyword ==> GO terms and Genes
- [ ] Genes ==> Functional Annotations

==========
EXPRESSION
- [x] Expression ==> Genes
- [x] Genes ==> RNA-seq Expression

==========
GENETICS
- [x] Trait (TO Term) ==> QTLs

==========
PUBLICATIONS
- [x] Name ==> Publication
- [x] Keyword ==> Publication

**Comment by sammyjava** [comment]
I think we got all these that are distinct and doable.

**Comment by adf-ncgr** [comment]
looking good- any reason I should not point the relevant soybean folks to the ostensibly finished product?

**Comment by sammyjava** [comment]
Feel free.
